### PR TITLE
remove projections.jl

### PR DESCRIPTION
**Pull request by visr**
Since https://github.com/JuliaGeo/Proj4.jl/pull/51 was released, we can now simplify the projection code here. Here I chose to go all the way and just delete projections.jl altogether. Let me know what you think. If desired, we could bring back the `WinkelTripel()` et al helper functions, though I figured people could just use the proj strings directly, we won't wrap them all anyway.

I changed the README image a bit, since it felt a bit weird strange to show US states on a zoomed out world map. The download and pulling the data through GeoInterface is also a bit slow, but we could work on that later.

image

### CODE REVIEW

**Comment by Datseris** [comment]
How well does this play with (a) datasets that have 0:360 as the longitude grid, and (b) giving a "shift longitude" as an option? I remember this was a major problem when I was using GeoMakie, where the only way to actually use it was to transform my data to start from -180 to 180, which was a hassle.

**Comment by visr** [comment]
Ah yes, this was a bit difficult in #7. Right now we are just directly using PROJ, so I'm reading https://proj.org/usage/projections.html#longitude-wrapping again. Trying out some examples I think we have to ignore my comment [here](https://github.com/JuliaPlots/GeoMakie.jl/issues/7#issuecomment-581078328) about the `+lon_0` option.

I believe you wanted to plot coordinates with longitudes in the range 0 to 360, with the central meridian in the center, and not having to transform your longitudes to -180:180 yourself. The example below seems to meet those criteria. So I add 180 degrees longitude to make the points fall in 0:360. Then I use `"+lon_0=180"`, to put the central meridian in the desired place.

```julia
using Proj4, CairoMakie, StaticArrays

begin
    trans = Proj4.Transformation("+proj=longlat +datum=WGS84", "+proj=robin +lon_0=180", always_xy=true)
    ptrans = Makie.PointTrans{2}(trans)

    fig = Figure()
    ax = Axis(fig[1,1], aspect = DataAspect())

    # all input data coordinates are projected using this function
    ax.scene.transformation.transform_func[] = ptrans

    # draw projected grid lines and set limits accordingly
    # lons = -180:10:180
    lons = 0:10:360
    lats = -90:10:90
    field = [exp(cosd(l)) + 3(y/90) for l in lons, y in lats]
    points = map(CartesianIndices(size(field))) do xy
        x, y = Tuple(xy)
        Point2f0(lons[x], lats[y])
    end
    limits = FRect2D(Makie.apply_transform(ptrans, points))
    limits!(ax, limits)
    wireframe!(ax, lons, lats, field, color=(:gray, 0.2), transparency=true)

    # add grey dots for populated places
    pop = Downloads.download(url * "ne_10m_populated_places_simple.geojson", IOBuffer())
    pop_geo = GeoJSON.read(seekstart(pop))
    pop_gb = GeoMakie.geo2basic(pop_geo)
    pop_gb_360 = pop_gb .+ Ref(SA_F32[180, 0])
    scatter!(ax, pop_gb_360, color="black", markersize=1.5)

    hidedecorations!(ax)
    hidespines!(ax)
    display(fig)
end
```

image

Without `"+lon_0=180"` it would look like this:

image

**Comment by lazarusA** [comment]
it would nice to have the corresponding lon,lat coordinates.

**Comment by visr** [comment]
Thanks, this does the same, added to the readme example. (I made a few less gridlines to keep the tick labels visible.)
```julia
ax.xticks = (first.(trans.(Point2.(lons, 0))), string.(lons, 'ᵒ'))
ax.yticks = (last.(trans.(Point2.(0, lats))), string.(lats, 'ᵒ'))
```
image

From the gridline you can see this works for latitudes, which are straight grid lines. For longitude however the ticks only apply to the equator, so perhaps they should be placed there? Or something like this:

image

Though perhaps we should work on better examples including ticks, and perhaps some convenience function that make this easier, in a separate PR?

**Comment by lazarusA** [comment]
Indeed looks simpler. However, now the grid lines look broken, due to the number of sample points along each line. That's why I defined each line independently. But, for now probably is ok and this can be done in different issue.

**Comment by lazarusA** [comment]
Also, the way it is, New Zealand is out. So probably your current approach to draw those lines is not ideal, ?

**Comment by visr** [comment]
Ah haha, I guess 180 east is wrapped to 170 west, and drawn twice there. We'd need to `prevfloat(180.0)` or something like that to draw the 180 east grid line.

**Comment by visr** [comment]
New Zealand has rejoined the Earth, I also updated the picture in the top post / README.

**Review by SimonDanisch — APPROVED** [review]

**Pull request merged**
