### PR TITLE
start anew

### PR DESCRIPTION
**Pull request by SimonDanisch**
* rip out anything unused / not working
* start with simple conversions
* leave the heavy lifting to AbstractPlotting
* switch to gh-actions

Status:
```julia
begin
    lons = LinRange(-179.5, 179.5, 360 ÷ 2)
    lats = LinRange(-89.5, 89.5, 180 ÷ 2)
    field = [exp(cosd(l)) + 3(y/90) for l in lons, y in lats]
    fig = Figure()
    ax = fig[1,1] = Axis(fig)
    ax.scene.transformation.transform_func[] = proj_trans
    wireframe!(ax, lons, lats, field, color=(:gray, 0.2), transparency=true)
    n = length(GeoInterface.features(states_geo))
    lines!(ax, coastlines())
    poly!(ax, states_geo, color= 1:n, strokecolor = :blue, strokewidth = 1)
    display(fig)
end
```
image

### CODE REVIEW

**Comment by visr** [comment]
This is pretty awesome, great work! Nice to see that the amount of lines of code could be reduced so much. If I understand correctly this still needs https://github.com/JuliaPlots/AbstractPlotting.jl/pull/600.

Some of the projection code should be able to be reduced furher in the new version of Proj4.jl that I'm working on, but I think it's good to just merge this, and work from there.

**Comment by SimonDanisch** [comment]
We'll fix the docs once the API is more stable and usable!!

**Comment by lazarusA** [comment]
Great!
I can confirm that this works with GLMakie, but in my case I did not see any output using CairoMakie.
well, the output is just a big rectangle with the grid lines, but no map.

**Comment by SimonDanisch** [comment]
Yeah, the other backends still need a PR like this one: https://github.com/JuliaPlots/GLMakie.jl/pull/159

**Pull request merged**
